"""enforce_referential_integrity_and_cascades

Revision ID: 2770c37f0caa
Revises: 9b21f39ad62f
Create Date: 2026-06-17 15:42:39.770873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2770c37f0caa'
down_revision: Union[str, Sequence[str], None] = '9b21f39ad62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_employee_id_fkey'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'roles', ['role'], ['name'], onupdate='CASCADE')
    op.create_foreign_key(None, 'accounts', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('employee_skills_employee_id_fkey'), 'employee_skills', type_='foreignkey')
    op.create_foreign_key(None, 'employee_skills', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('employees_manager_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'roles', ['role'], ['name'], onupdate='CASCADE')
    op.create_foreign_key(None, 'employees', 'departments', ['department'], ['name'], onupdate='CASCADE')
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'project_members', ['project_id', 'employee_id'])
    op.drop_constraint(op.f('project_members_employee_id_fkey'), 'project_members', type_='foreignkey')
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_members_employee_id_fkey'), 'project_members', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'project_members', type_='unique')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_manager_id_fkey'), 'employees', 'employees', ['manager_id'], ['id'])
    op.drop_constraint(None, 'employee_skills', type_='foreignkey')
    op.create_foreign_key(op.f('employee_skills_employee_id_fkey'), 'employee_skills', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_employee_id_fkey'), 'accounts', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
