"""add_fk_to_role_permissions

Revision ID: e2dce050defe
Revises: 2770c37f0caa
Create Date: 2026-06-17 15:46:58.172204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dce050defe'
down_revision: Union[str, Sequence[str], None] = '2770c37f0caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_name'], ['name'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    # ### end Alembic commands ###
