/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#c3c0ff",
        "outline": "#777587",
        "surface-container-high": "#eae6f3",
        "surface": "#fcf8ff",
        "primary": "#3e32d3",
        "tertiary-container": "#ae4a00",
        "on-surface-variant": "#464555",
        "primary-container": "#5850ec",
        "outline-variant": "#c7c4d8",
        "surface-container-highest": "#e4e1ee",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "error-container": "#ffdad6",
        "on-surface": "#1b1b24",
        "on-secondary-container": "#454385",
        "secondary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#793100",
        "secondary-container": "#b6b4ff",
        "on-tertiary-fixed": "#341100",
        "on-secondary-fixed": "#140f53",
        "inverse-surface": "#302f39",
        "background": "#fcf8ff",
        "on-primary-fixed-variant": "#3424ca",
        "tertiary-fixed-dim": "#ffb691",
        "surface-tint": "#4e44e2",
        "inverse-on-surface": "#f3effc",
        "surface-bright": "#fcf8ff",
        "surface-dim": "#dcd8e5",
        "on-secondary-fixed-variant": "#413f81",
        "primary-fixed": "#e2dfff",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e1ee",
        "surface-container": "#f0ecf9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffe3d6",
        "error": "#ba1a1a",
        "surface-container-low": "#f5f2ff",
        "secondary-fixed-dim": "#c3c0ff",
        "tertiary-fixed": "#ffdbcb",
        "on-primary-container": "#e9e5ff",
        "secondary": "#59579a",
        "on-primary": "#ffffff",
        "on-background": "#1b1b24",
        "tertiary": "#883800"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-md": "1.5rem",
        "container-max": "1800px",
        "stack-xs": "0.5rem",
        "margin-desktop": "40px",
        "stack-xl": "3rem",
        "unit": "4px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-xl": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-xs": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "display-xl": ["3.5rem", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "body-md": ["1rem", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["1.5rem", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["1.125rem", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "label-xs": ["0.75rem", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-sm": ["0.875rem", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg": ["2.25rem", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg-mobile": ["1.75rem", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
